# unemployment data visualization 
### 1. test data: 2007 unemployment rate
### 2. 2006-2014 9 countries unemployment rate visualization

In [3]:
import csv
import pandas as pd
import plotly.plotly as py
import plotly.graph_objs as go

#2007 data visualization 
unemployment = pd.read_csv('unemployment.csv')
unemployment
country = unemployment['country name']
data2007 = unemployment['2007']

#set: x axis data, y axis data, line color and width 
trace0 = go.Scatter(
    x = country,
    y = data2007,
    name = '2007',
    line = dict(
        color = ('rgb(205, 12, 24)'),
        width = 4)
)
data = [trace0]

#set layout: title, xaxis, yaxis 
layout = dict(title = 'Unemployment Rate Change',
              xaxis = dict(title = 'country name'),
              yaxis = dict(title = 'unemploytment %'),
              )

fig = dict(data=data, layout=layout)
py.iplot(fig, filename='styled-line')

In [5]:
import csv
import pandas as pd

import plotly.plotly as py
import plotly.graph_objs as go

unemployment = pd.read_csv('unemployment.csv')
unemployment
country = unemployment['country name']
data2007 = unemployment['2007']

trace0 = go.Scatter(
    x = data2007,
    y = country,
    name = '2007',
    line = dict(
        color = ('rgb(25, 129, 240)'),
        width = 4)
)
data = [trace0]
layout = dict(title = 'Unemployment Rate Change',
              xaxis = dict(title = 'unemployment rate'),
              yaxis = dict(title = 'country name'),
              )

fig = dict(data=data, layout=layout)
py.iplot(fig, filename='styled-line')

In [23]:
columnsData = unemployment.loc[2,]
columnsData[0]

#columsData

'south_korea'

### data processing for visualization

In [63]:
unemployment1 = unemployment.T  #transpose unemployment data for visualization 
unemployment1.iloc[ : , 3] 

#record necessary data in each variable / using loc, iloc 
country= unemployment1.iloc[ 0 , : ]
unemployment2 = unemployment1.iloc[1:,:]
unemployment2
spain = unemployment2.iloc[ : , 0]
philippines= unemployment2.iloc[ : , 1]
south_korea=unemployment2.iloc[ : , 2]
mexico=unemployment2.iloc[ : , 3]
austria=unemployment2.iloc[ : , 4]
poland=unemployment2.iloc[ : , 5]
portugal=unemployment2.iloc[ : , 6]
egypt=unemployment2.iloc[ : , 7]
denmark=unemployment2.iloc[ : , 8]
australia=unemployment2.iloc[ : , 9]
unemployment

  country name  2006  2007  2008  2009  2010  2011  2012 2013  2014
0        spain   8.4   8.2  11.0  17.0  19.0  21.0  24.0  26.  24.0
1  philippines   7.9   7.3   7.4   7.4   7.3   7.0   6.9  7.0   6.8
2  south_korea   3.4   3.2   3.1   3.6   3.7   3.4   3.2  3.1   3.5
3       mexico   3.5   3.6   3.8   5.3   5.2   5.1   4.8  4.9   4.7
4      austria   4.7   4.4   3.8   4.7   4.4   4.1   4.3  4.9   5.0
5       poland  13.0   9.6   7.1   8.1   9.6   9.6  10.0  10.   8.9
6     portugal   7.6   7.9   7.5   9.4  10.0  12.0  15.0  16.  13.0
7        egypt  10.0   9.2   8.6   9.3   9.2  10.0  12.0  13<  13.0
8      denmark   3.9   3.7   3.4   5.9   7.4   7.5   7.5  7.0   6.5
9    australia   4.7   4.3   4.2   5.5   5.2   5.0   5.2  5.6   6.0

### Unemployment rate change graph (2006-2014/  9 countries)

In [1]:
import csv
import pandas as pd

import plotly.plotly as py
import plotly.graph_objs as go

unemployment = pd.read_csv('unemployment.csv')
unemployment1 = unemployment.T
unemployment1.iloc[ : , 3]
year = ['2006','2007','2008','2009','2010','2011','2012','2013','2014']  #x-axis data 
country= unemployment1.iloc[ 0 , : ]
unemployment2 = unemployment1.iloc[1:,:]
unemployment2
spain = unemployment2.iloc[ : , 0]
philippines= unemployment2.iloc[ : , 1]
south_korea=unemployment2.iloc[ : , 2]
mexico=unemployment2.iloc[ : , 3]
austria=unemployment2.iloc[ : , 4]
poland=unemployment2.iloc[ : , 5]
portugal=unemployment2.iloc[ : , 6]
egypt=unemployment2.iloc[ : , 7]
denmark=unemployment2.iloc[ : , 8]
australia=unemployment2.iloc[ : , 9]

#each trace = each country's unemployment data 

#trace: xaxis, yaxis, line color, lind width 
trace0 = go.Scatter(
    x = year,
    y = spain,
    name = 'spain',
    line = dict(
        color = ('rgb(205, 12, 24)'),
        width = 4)
)

trace1 = go.Scatter(
    x = year,
    y = philippines,
    name = 'philippines',
    line = dict(
        color = ('rgb(400, 200, 24)'),
        width = 4)
)
trace2 = go.Scatter(
    x = year,
    y = south_korea,
    name = 'south_korea',
    line = dict(
        color = ('rgb(800, 200, 124)'),
        width = 4)
)
trace3 = go.Scatter(
    x = year,
    y = mexico,
    name = 'mexico',
    line = dict(
        color = ('rgb(20, 600, 4)'),
        width = 4)
)

trace4 = go.Scatter(
    x = year,
    y = austria,
    name = 'austria',
    line = dict(
        color = ('rgb(500, 10, 44)'),
        width = 4)
)

trace5 = go.Scatter(
    x = year,
    y = poland,
    name = 'poland',
    line = dict(
        color = ('rgb(900,2,400)'),
        width = 4)
)

trace6 = go.Scatter(
    x = year,
    y = portugal,
    name = 'portugal',
    line = dict(
        color = ('rgb(200, 800, 400)'),
        width = 4)
)

trace7 = go.Scatter(
    x = year,
    y = egypt,
    name = 'egypt',
    line = dict(
        color = ('rgb(2, 600, 400)'),
        width = 4)
)

trace8 = go.Scatter(
    x = year,
    y = denmark,
    name = 'denmark',
    line = dict(
        color = ('rgb(2, 100, 4)'),
        width = 4)
)

data = [trace0, trace1,trace2, trace3, trace4, trace5, trace6, trace7, trace8]
#set layout: title, xaxis, yaxis 
layout = dict(title = 'Unemployment Rate Change',
              xaxis = dict(title = 'Year'),
              yaxis = dict(title = 'Unemployment %'),
    
              )

fig = dict(data=data, layout=layout)
py.iplot(fig, filename='legend-names')